name: epub_view_example
description: Example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  epub_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/font_sizes/
    - assets/icons/line_spaces/
    - assets/icons/navigation/
    - assets/images/

  uses-material-design: true
