name: epub_view_example
description: Example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  epub_view:
    path: ../
  flutter_bloc: ^8.1.2
  permission_handler: ^10.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  assets:
    - assets/
    - assets/epub_books/
    - assets/icons/
    - assets/icons/font_sizes/
    - assets/icons/line_spaces/
    - assets/icons/navigation/
    - assets/images/

  uses-material-design: true
